// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Id       int64  `json:"id"`
	Token    string `json:"token"`
	ExpireAt string `json:"expireAt"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type ResisterResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}



type GetUserInfoReq struct {
	Id int64 `json:"id"`
}

type GetUserInfoResp struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
	Desc string `json:"desc"`
}

type UpdateUserInfoReq struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
	Desc string `json:"desc"`
}

type AddPostComment struct {
	PostID  int64  `json:"postId"`
	Content string `json:"content"`
}

type AddPostInfoReq struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type CommentInfo struct {
	ID      int64  `json:"id"`
	Content string `json:"content"`
	UserID  uint   `json:"userId"`
	PostID  int64  `json:"postId"`
}

type GetPostById struct {
	ID int64 `path:"id"` //路径方式
}

type GetPostInfoReq struct {
	UserId int64 `json:"userId"`
}

type PostInfo struct {
	ID        int64         `json:"id"`
	Title     string        `json:"title"`
	Content   string        `json:"content"`
	UserID    int64         `json:"userId"`
	CmtStatus string        `json:"cmtStatus"`
	Comments  []CommentInfo `json:"comments"` //返回评论列表
}
