// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	blog "blogV2/gateway-api/internal/handler/blog"
	login "blogV2/gateway-api/internal/handler/login"
	user "blogV2/gateway-api/internal/handler/user"
	"blogV2/gateway-api/internal/svc"
	"net/http"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: login.LoginHandler(serverCtx),
			},
			{
				// 注册
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: login.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/blog/v2"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/info",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/info/update",
				Handler: user.UpdateUserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret), // 使用内置JWT中间件
		// 或者使用自定义中间件:
		// rest.WithMiddlewares([]rest.Middleware{serverCtx.JwtMiddleware.Handle})
		rest.WithPrefix("/api/blog/v2"),
	)
	server.AddRoutes(
		[]rest.Route{
			{
				// 查询当前用户的文章
				Method:  http.MethodGet,
				Path:    "/myPost",
				Handler: blog.GetCurrentPostHandler(serverCtx),
			},
			{
				// 根据用户id查询所以文章
				Method:  http.MethodGet,
				Path:    "/post",
				Handler: blog.GetPostByUserIdHandler(serverCtx),
			},
			{
				// 根据文章id查询文章
				Method:  http.MethodPost,
				Path:    "/post/:id",
				Handler: blog.GetPostByIdHandler(serverCtx),
			},
			{
				// 删除文章
				Method:  http.MethodDelete,
				Path:    "/post/:id",
				Handler: blog.DeletePostHandler(serverCtx),
			},
			{
				// 添加评论
				Method:  http.MethodPost,
				Path:    "/post/comment",
				Handler: blog.AddPostCommentHandler(serverCtx),
			},
			{
				// 获取文章的所有评论列表
				Method:  http.MethodPost,
				Path:    "/post/comments",
				Handler: blog.GetPostCommentsHandler(serverCtx),
			},
			{
				// 添加文章
				Method:  http.MethodPost,
				Path:    "/post/create",
				Handler: blog.AddPostHandler(serverCtx),
			},
			{
				// 修改文章
				Method:  http.MethodPost,
				Path:    "/post/update/:id",
				Handler: blog.UpdatePostHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret), // 使用内置JWT中间件
		// 或者使用自定义中间件:
		// rest.WithMiddlewares([]rest.Middleware{serverCtx.JwtMiddleware.Handle})
		rest.WithPrefix("/api/blog/v2"),
	)
}
