// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: blog.proto

package server

import (
	"context"

	"blogV2/blog-rpc/blog"
	"blogV2/blog-rpc/internal/logic"
	"blogV2/blog-rpc/internal/svc"
)

type BlogServer struct {
	svcCtx *svc.ServiceContext
	blog.UnimplementedBlogServer
}

func NewBlogServer(svcCtx *svc.ServiceContext) *BlogServer {
	return &BlogServer{
		svcCtx: svcCtx,
	}
}

// 根据文章id查询文章
func (s *BlogServer) GetPostById(ctx context.Context, in *blog.GetPostByIdReq) (*blog.PostInfo, error) {
	l := logic.NewGetPostByIdLogic(ctx, s.svcCtx)
	return l.GetPostById(in)
}

// 根据用户id查询所有文章
func (s *BlogServer) GetPostByUserId(ctx context.Context, in *blog.GetPostByUserIdReq) (*blog.GetPostByUserIdResp, error) {
	l := logic.NewGetPostByUserIdLogic(ctx, s.svcCtx)
	return l.GetPostByUserId(in)
}

// 查询当前用户的文章
func (s *BlogServer) GetCurrentPost(ctx context.Context, in *blog.GetCurrentPostReq) (*blog.GetCurrentPostResp, error) {
	l := logic.NewGetCurrentPostLogic(ctx, s.svcCtx)
	return l.GetCurrentPost(in)
}

// 添加文章
func (s *BlogServer) AddPost(ctx context.Context, in *blog.AddPostReq) (*blog.AddPostResp, error) {
	l := logic.NewAddPostLogic(ctx, s.svcCtx)
	return l.AddPost(in)
}

// 修改文章
func (s *BlogServer) UpdatePost(ctx context.Context, in *blog.UpdatePostReq) (*blog.UpdatePostResp, error) {
	l := logic.NewUpdatePostLogic(ctx, s.svcCtx)
	return l.UpdatePost(in)
}

// 删除文章
func (s *BlogServer) DeletePost(ctx context.Context, in *blog.DeletePostReq) (*blog.DeletePostResp, error) {
	l := logic.NewDeletePostLogic(ctx, s.svcCtx)
	return l.DeletePost(in)
}

// 添加评论
func (s *BlogServer) AddPostComment(ctx context.Context, in *blog.AddPostCommentReq) (*blog.AddPostCommentResp, error) {
	l := logic.NewAddPostCommentLogic(ctx, s.svcCtx)
	return l.AddPostComment(in)
}

// 获取文章的所有评论列表
func (s *BlogServer) GetPostComments(ctx context.Context, in *blog.GetPostCommentsReq) (*blog.GetPostCommentsResp, error) {
	l := logic.NewGetPostCommentsLogic(ctx, s.svcCtx)
	return l.GetPostComments(in)
}
