// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: blog.proto

package blogClient

import (
	"context"

	"blogV2/blog-rpc/blog"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddPostCommentReq   = blog.AddPostCommentReq
	AddPostCommentResp  = blog.AddPostCommentResp
	AddPostReq          = blog.AddPostReq
	AddPostResp         = blog.AddPostResp
	CommentInfo         = blog.CommentInfo
	DeletePostReq       = blog.DeletePostReq
	DeletePostResp      = blog.DeletePostResp
	GetCurrentPostReq   = blog.GetCurrentPostReq
	GetCurrentPostResp  = blog.GetCurrentPostResp
	GetPostByIdReq      = blog.GetPostByIdReq
	GetPostByUserIdReq  = blog.GetPostByUserIdReq
	GetPostByUserIdResp = blog.GetPostByUserIdResp
	GetPostCommentsReq  = blog.GetPostCommentsReq
	GetPostCommentsResp = blog.GetPostCommentsResp
	PostInfo            = blog.PostInfo
	UpdatePostReq       = blog.UpdatePostReq
	UpdatePostResp      = blog.UpdatePostResp

	Blog interface {
		// 根据文章id查询文章
		GetPostById(ctx context.Context, in *GetPostByIdReq, opts ...grpc.CallOption) (*PostInfo, error)
		// 根据用户id查询所有文章
		GetPostByUserId(ctx context.Context, in *GetPostByUserIdReq, opts ...grpc.CallOption) (*GetPostByUserIdResp, error)
		// 查询当前用户的文章
		GetCurrentPost(ctx context.Context, in *GetCurrentPostReq, opts ...grpc.CallOption) (*GetCurrentPostResp, error)
		// 添加文章
		AddPost(ctx context.Context, in *AddPostReq, opts ...grpc.CallOption) (*AddPostResp, error)
		// 修改文章
		UpdatePost(ctx context.Context, in *UpdatePostReq, opts ...grpc.CallOption) (*UpdatePostResp, error)
		// 删除文章
		DeletePost(ctx context.Context, in *DeletePostReq, opts ...grpc.CallOption) (*DeletePostResp, error)
		// 添加评论
		AddPostComment(ctx context.Context, in *AddPostCommentReq, opts ...grpc.CallOption) (*AddPostCommentResp, error)
		// 获取文章的所有评论列表
		GetPostComments(ctx context.Context, in *GetPostCommentsReq, opts ...grpc.CallOption) (*GetPostCommentsResp, error)
	}

	defaultBlog struct {
		cli zrpc.Client
	}
)

func NewBlog(cli zrpc.Client) Blog {
	return &defaultBlog{
		cli: cli,
	}
}

// 根据文章id查询文章
func (m *defaultBlog) GetPostById(ctx context.Context, in *GetPostByIdReq, opts ...grpc.CallOption) (*PostInfo, error) {
	client := blog.NewBlogClient(m.cli.Conn())
	return client.GetPostById(ctx, in, opts...)
}

// 根据用户id查询所有文章
func (m *defaultBlog) GetPostByUserId(ctx context.Context, in *GetPostByUserIdReq, opts ...grpc.CallOption) (*GetPostByUserIdResp, error) {
	client := blog.NewBlogClient(m.cli.Conn())
	return client.GetPostByUserId(ctx, in, opts...)
}

// 查询当前用户的文章
func (m *defaultBlog) GetCurrentPost(ctx context.Context, in *GetCurrentPostReq, opts ...grpc.CallOption) (*GetCurrentPostResp, error) {
	client := blog.NewBlogClient(m.cli.Conn())
	return client.GetCurrentPost(ctx, in, opts...)
}

// 添加文章
func (m *defaultBlog) AddPost(ctx context.Context, in *AddPostReq, opts ...grpc.CallOption) (*AddPostResp, error) {
	client := blog.NewBlogClient(m.cli.Conn())
	return client.AddPost(ctx, in, opts...)
}

// 修改文章
func (m *defaultBlog) UpdatePost(ctx context.Context, in *UpdatePostReq, opts ...grpc.CallOption) (*UpdatePostResp, error) {
	client := blog.NewBlogClient(m.cli.Conn())
	return client.UpdatePost(ctx, in, opts...)
}

// 删除文章
func (m *defaultBlog) DeletePost(ctx context.Context, in *DeletePostReq, opts ...grpc.CallOption) (*DeletePostResp, error) {
	client := blog.NewBlogClient(m.cli.Conn())
	return client.DeletePost(ctx, in, opts...)
}

// 添加评论
func (m *defaultBlog) AddPostComment(ctx context.Context, in *AddPostCommentReq, opts ...grpc.CallOption) (*AddPostCommentResp, error) {
	client := blog.NewBlogClient(m.cli.Conn())
	return client.AddPostComment(ctx, in, opts...)
}

// 获取文章的所有评论列表
func (m *defaultBlog) GetPostComments(ctx context.Context, in *GetPostCommentsReq, opts ...grpc.CallOption) (*GetPostCommentsResp, error) {
	client := blog.NewBlogClient(m.cli.Conn())
	return client.GetPostComments(ctx, in, opts...)
}
