// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package userCenterClient

import (
	"context"

	"blogV2/user-rpc/usercenter"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUserInfoReq     = usercenter.GetUserInfoReq
	GetUserInfoResp    = usercenter.GetUserInfoResp
	LoginReq           = usercenter.LoginReq
	LoginResp          = usercenter.LoginResp
	RegisterReq        = usercenter.RegisterReq
	RegisterResp       = usercenter.RegisterResp
	UpdateUserInfoReq  = usercenter.UpdateUserInfoReq
	UpdateUserInfoResp = usercenter.UpdateUserInfoResp

	UserCenter interface {
		// 用户注册
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		// 用户登录
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		// 获取用户信息
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		// 更新用户信息
		UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*UpdateUserInfoResp, error)
	}

	defaultUserCenter struct {
		cli zrpc.Client
	}
)

func NewUserCenter(cli zrpc.Client) UserCenter {
	return &defaultUserCenter{
		cli: cli,
	}
}

// 用户注册
func (m *defaultUserCenter) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := usercenter.NewUserCenterClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

// 用户登录
func (m *defaultUserCenter) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := usercenter.NewUserCenterClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// 获取用户信息
func (m *defaultUserCenter) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := usercenter.NewUserCenterClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

// 更新用户信息
func (m *defaultUserCenter) UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*UpdateUserInfoResp, error) {
	client := usercenter.NewUserCenterClient(m.cli.Conn())
	return client.UpdateUserInfo(ctx, in, opts...)
}
