// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: blog.proto

package blog

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Blog_GetPostById_FullMethodName     = "/blog.Blog/GetPostById"
	Blog_GetPostByUserId_FullMethodName = "/blog.Blog/GetPostByUserId"
	Blog_GetCurrentPost_FullMethodName  = "/blog.Blog/GetCurrentPost"
	Blog_AddPost_FullMethodName         = "/blog.Blog/AddPost"
	Blog_UpdatePost_FullMethodName      = "/blog.Blog/UpdatePost"
	Blog_DeletePost_FullMethodName      = "/blog.Blog/DeletePost"
	Blog_AddPostComment_FullMethodName  = "/blog.Blog/AddPostComment"
	Blog_GetPostComments_FullMethodName = "/blog.Blog/GetPostComments"
)

// BlogClient is the client API for Blog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 博客服务
type BlogClient interface {
	// 根据文章id查询文章
	GetPostById(ctx context.Context, in *GetPostByIdReq, opts ...grpc.CallOption) (*PostInfo, error)
	// 根据用户id查询所有文章
	GetPostByUserId(ctx context.Context, in *GetPostByUserIdReq, opts ...grpc.CallOption) (*GetPostByUserIdResp, error)
	// 查询当前用户的文章
	GetCurrentPost(ctx context.Context, in *GetCurrentPostReq, opts ...grpc.CallOption) (*GetCurrentPostResp, error)
	// 添加文章
	AddPost(ctx context.Context, in *AddPostReq, opts ...grpc.CallOption) (*AddPostResp, error)
	// 修改文章
	UpdatePost(ctx context.Context, in *UpdatePostReq, opts ...grpc.CallOption) (*UpdatePostResp, error)
	// 删除文章
	DeletePost(ctx context.Context, in *DeletePostReq, opts ...grpc.CallOption) (*DeletePostResp, error)
	// 添加评论
	AddPostComment(ctx context.Context, in *AddPostCommentReq, opts ...grpc.CallOption) (*AddPostCommentResp, error)
	// 获取文章的所有评论列表
	GetPostComments(ctx context.Context, in *GetPostCommentsReq, opts ...grpc.CallOption) (*GetPostCommentsResp, error)
}

type blogClient struct {
	cc grpc.ClientConnInterface
}

func NewBlogClient(cc grpc.ClientConnInterface) BlogClient {
	return &blogClient{cc}
}

func (c *blogClient) GetPostById(ctx context.Context, in *GetPostByIdReq, opts ...grpc.CallOption) (*PostInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostInfo)
	err := c.cc.Invoke(ctx, Blog_GetPostById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) GetPostByUserId(ctx context.Context, in *GetPostByUserIdReq, opts ...grpc.CallOption) (*GetPostByUserIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPostByUserIdResp)
	err := c.cc.Invoke(ctx, Blog_GetPostByUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) GetCurrentPost(ctx context.Context, in *GetCurrentPostReq, opts ...grpc.CallOption) (*GetCurrentPostResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentPostResp)
	err := c.cc.Invoke(ctx, Blog_GetCurrentPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) AddPost(ctx context.Context, in *AddPostReq, opts ...grpc.CallOption) (*AddPostResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPostResp)
	err := c.cc.Invoke(ctx, Blog_AddPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) UpdatePost(ctx context.Context, in *UpdatePostReq, opts ...grpc.CallOption) (*UpdatePostResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePostResp)
	err := c.cc.Invoke(ctx, Blog_UpdatePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) DeletePost(ctx context.Context, in *DeletePostReq, opts ...grpc.CallOption) (*DeletePostResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePostResp)
	err := c.cc.Invoke(ctx, Blog_DeletePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) AddPostComment(ctx context.Context, in *AddPostCommentReq, opts ...grpc.CallOption) (*AddPostCommentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPostCommentResp)
	err := c.cc.Invoke(ctx, Blog_AddPostComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) GetPostComments(ctx context.Context, in *GetPostCommentsReq, opts ...grpc.CallOption) (*GetPostCommentsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPostCommentsResp)
	err := c.cc.Invoke(ctx, Blog_GetPostComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlogServer is the server API for Blog service.
// All implementations must embed UnimplementedBlogServer
// for forward compatibility.
//
// 博客服务
type BlogServer interface {
	// 根据文章id查询文章
	GetPostById(context.Context, *GetPostByIdReq) (*PostInfo, error)
	// 根据用户id查询所有文章
	GetPostByUserId(context.Context, *GetPostByUserIdReq) (*GetPostByUserIdResp, error)
	// 查询当前用户的文章
	GetCurrentPost(context.Context, *GetCurrentPostReq) (*GetCurrentPostResp, error)
	// 添加文章
	AddPost(context.Context, *AddPostReq) (*AddPostResp, error)
	// 修改文章
	UpdatePost(context.Context, *UpdatePostReq) (*UpdatePostResp, error)
	// 删除文章
	DeletePost(context.Context, *DeletePostReq) (*DeletePostResp, error)
	// 添加评论
	AddPostComment(context.Context, *AddPostCommentReq) (*AddPostCommentResp, error)
	// 获取文章的所有评论列表
	GetPostComments(context.Context, *GetPostCommentsReq) (*GetPostCommentsResp, error)
	mustEmbedUnimplementedBlogServer()
}

// UnimplementedBlogServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlogServer struct{}

func (UnimplementedBlogServer) GetPostById(context.Context, *GetPostByIdReq) (*PostInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostById not implemented")
}
func (UnimplementedBlogServer) GetPostByUserId(context.Context, *GetPostByUserIdReq) (*GetPostByUserIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostByUserId not implemented")
}
func (UnimplementedBlogServer) GetCurrentPost(context.Context, *GetCurrentPostReq) (*GetCurrentPostResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentPost not implemented")
}
func (UnimplementedBlogServer) AddPost(context.Context, *AddPostReq) (*AddPostResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPost not implemented")
}
func (UnimplementedBlogServer) UpdatePost(context.Context, *UpdatePostReq) (*UpdatePostResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePost not implemented")
}
func (UnimplementedBlogServer) DeletePost(context.Context, *DeletePostReq) (*DeletePostResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePost not implemented")
}
func (UnimplementedBlogServer) AddPostComment(context.Context, *AddPostCommentReq) (*AddPostCommentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPostComment not implemented")
}
func (UnimplementedBlogServer) GetPostComments(context.Context, *GetPostCommentsReq) (*GetPostCommentsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostComments not implemented")
}
func (UnimplementedBlogServer) mustEmbedUnimplementedBlogServer() {}
func (UnimplementedBlogServer) testEmbeddedByValue()              {}

// UnsafeBlogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlogServer will
// result in compilation errors.
type UnsafeBlogServer interface {
	mustEmbedUnimplementedBlogServer()
}

func RegisterBlogServer(s grpc.ServiceRegistrar, srv BlogServer) {
	// If the following call pancis, it indicates UnimplementedBlogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Blog_ServiceDesc, srv)
}

func _Blog_GetPostById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).GetPostById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blog_GetPostById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).GetPostById(ctx, req.(*GetPostByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_GetPostByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostByUserIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).GetPostByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blog_GetPostByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).GetPostByUserId(ctx, req.(*GetPostByUserIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_GetCurrentPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentPostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).GetCurrentPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blog_GetCurrentPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).GetCurrentPost(ctx, req.(*GetCurrentPostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_AddPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).AddPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blog_AddPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).AddPost(ctx, req.(*AddPostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blog_UpdatePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).UpdatePost(ctx, req.(*UpdatePostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blog_DeletePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).DeletePost(ctx, req.(*DeletePostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_AddPostComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPostCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).AddPostComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blog_AddPostComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).AddPostComment(ctx, req.(*AddPostCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_GetPostComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostCommentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).GetPostComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blog_GetPostComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).GetPostComments(ctx, req.(*GetPostCommentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Blog_ServiceDesc is the grpc.ServiceDesc for Blog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Blog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blog.Blog",
	HandlerType: (*BlogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPostById",
			Handler:    _Blog_GetPostById_Handler,
		},
		{
			MethodName: "GetPostByUserId",
			Handler:    _Blog_GetPostByUserId_Handler,
		},
		{
			MethodName: "GetCurrentPost",
			Handler:    _Blog_GetCurrentPost_Handler,
		},
		{
			MethodName: "AddPost",
			Handler:    _Blog_AddPost_Handler,
		},
		{
			MethodName: "UpdatePost",
			Handler:    _Blog_UpdatePost_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _Blog_DeletePost_Handler,
		},
		{
			MethodName: "AddPostComment",
			Handler:    _Blog_AddPostComment_Handler,
		},
		{
			MethodName: "GetPostComments",
			Handler:    _Blog_GetPostComments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blog.proto",
}
