// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: blog.proto

package blog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPostByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostByIdReq) Reset() {
	*x = GetPostByIdReq{}
	mi := &file_blog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostByIdReq) ProtoMessage() {}

func (x *GetPostByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostByIdReq.ProtoReflect.Descriptor instead.
func (*GetPostByIdReq) Descriptor() ([]byte, []int) {
	return file_blog_proto_rawDescGZIP(), []int{0}
}

func (x *GetPostByIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPostByUserIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostByUserIdReq) Reset() {
	*x = GetPostByUserIdReq{}
	mi := &file_blog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostByUserIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostByUserIdReq) ProtoMessage() {}

func (x *GetPostByUserIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostByUserIdReq.ProtoReflect.Descriptor instead.
func (*GetPostByUserIdReq) Descriptor() ([]byte, []int) {
	return file_blog_proto_rawDescGZIP(), []int{1}
}

func (x *GetPostByUserIdReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetPostByUserIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*PostInfo            `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostByUserIdResp) Reset() {
	*x = GetPostByUserIdResp{}
	mi := &file_blog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostByUserIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostByUserIdResp) ProtoMessage() {}

func (x *GetPostByUserIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostByUserIdResp.ProtoReflect.Descriptor instead.
func (*GetPostByUserIdResp) Descriptor() ([]byte, []int) {
	return file_blog_proto_rawDescGZIP(), []int{2}
}

func (x *GetPostByUserIdResp) GetPosts() []*PostInfo {
	if x != nil {
		return x.Posts
	}
	return nil
}

type GetCurrentPostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentPostReq) Reset() {
	*x = GetCurrentPostReq{}
	mi := &file_blog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentPostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentPostReq) ProtoMessage() {}

func (x *GetCurrentPostReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentPostReq.ProtoReflect.Descriptor instead.
func (*GetCurrentPostReq) Descriptor() ([]byte, []int) {
	return file_blog_proto_rawDescGZIP(), []int{3}
}

func (x *GetCurrentPostReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetCurrentPostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*PostInfo            `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentPostResp) Reset() {
	*x = GetCurrentPostResp{}
	mi := &file_blog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentPostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentPostResp) ProtoMessage() {}

func (x *GetCurrentPostResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentPostResp.ProtoReflect.Descriptor instead.
func (*GetCurrentPostResp) Descriptor() ([]byte, []int) {
	return file_blog_proto_rawDescGZIP(), []int{4}
}

func (x *GetCurrentPostResp) GetPosts() []*PostInfo {
	if x != nil {
		return x.Posts
	}
	return nil
}

type AddPostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPostReq) Reset() {
	*x = AddPostReq{}
	mi := &file_blog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPostReq) ProtoMessage() {}

func (x *AddPostReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPostReq.ProtoReflect.Descriptor instead.
func (*AddPostReq) Descriptor() ([]byte, []int) {
	return file_blog_proto_rawDescGZIP(), []int{5}
}

func (x *AddPostReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddPostReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddPostReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddPostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPostResp) Reset() {
	*x = AddPostResp{}
	mi := &file_blog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPostResp) ProtoMessage() {}

func (x *AddPostResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPostResp.ProtoReflect.Descriptor instead.
func (*AddPostResp) Descriptor() ([]byte, []int) {
	return file_blog_proto_rawDescGZIP(), []int{6}
}

func (x *AddPostResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddPostResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdatePostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostReq) Reset() {
	*x = UpdatePostReq{}
	mi := &file_blog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostReq) ProtoMessage() {}

func (x *UpdatePostReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostReq.ProtoReflect.Descriptor instead.
func (*UpdatePostReq) Descriptor() ([]byte, []int) {
	return file_blog_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePostReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePostReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdatePostReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdatePostReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UpdatePostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostResp) Reset() {
	*x = UpdatePostResp{}
	mi := &file_blog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostResp) ProtoMessage() {}

func (x *UpdatePostResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostResp.ProtoReflect.Descriptor instead.
func (*UpdatePostResp) Descriptor() ([]byte, []int) {
	return file_blog_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePostResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdatePostResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeletePostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostReq) Reset() {
	*x = DeletePostReq{}
	mi := &file_blog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostReq) ProtoMessage() {}

func (x *DeletePostReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostReq.ProtoReflect.Descriptor instead.
func (*DeletePostReq) Descriptor() ([]byte, []int) {
	return file_blog_proto_rawDescGZIP(), []int{9}
}

func (x *DeletePostReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeletePostReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeletePostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostResp) Reset() {
	*x = DeletePostResp{}
	mi := &file_blog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostResp) ProtoMessage() {}

func (x *DeletePostResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostResp.ProtoReflect.Descriptor instead.
func (*DeletePostResp) Descriptor() ([]byte, []int) {
	return file_blog_proto_rawDescGZIP(), []int{10}
}

func (x *DeletePostResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeletePostResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddPostCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPostCommentReq) Reset() {
	*x = AddPostCommentReq{}
	mi := &file_blog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPostCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPostCommentReq) ProtoMessage() {}

func (x *AddPostCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPostCommentReq.ProtoReflect.Descriptor instead.
func (*AddPostCommentReq) Descriptor() ([]byte, []int) {
	return file_blog_proto_rawDescGZIP(), []int{11}
}

func (x *AddPostCommentReq) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *AddPostCommentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddPostCommentReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddPostCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPostCommentResp) Reset() {
	*x = AddPostCommentResp{}
	mi := &file_blog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPostCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPostCommentResp) ProtoMessage() {}

func (x *AddPostCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPostCommentResp.ProtoReflect.Descriptor instead.
func (*AddPostCommentResp) Descriptor() ([]byte, []int) {
	return file_blog_proto_rawDescGZIP(), []int{12}
}

func (x *AddPostCommentResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddPostCommentResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPostCommentsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostCommentsReq) Reset() {
	*x = GetPostCommentsReq{}
	mi := &file_blog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostCommentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostCommentsReq) ProtoMessage() {}

func (x *GetPostCommentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostCommentsReq.ProtoReflect.Descriptor instead.
func (*GetPostCommentsReq) Descriptor() ([]byte, []int) {
	return file_blog_proto_rawDescGZIP(), []int{13}
}

func (x *GetPostCommentsReq) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type GetPostCommentsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*CommentInfo         `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostCommentsResp) Reset() {
	*x = GetPostCommentsResp{}
	mi := &file_blog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostCommentsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostCommentsResp) ProtoMessage() {}

func (x *GetPostCommentsResp) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostCommentsResp.ProtoReflect.Descriptor instead.
func (*GetPostCommentsResp) Descriptor() ([]byte, []int) {
	return file_blog_proto_rawDescGZIP(), []int{14}
}

func (x *GetPostCommentsResp) GetComments() []*CommentInfo {
	if x != nil {
		return x.Comments
	}
	return nil
}

type PostInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	CmtStatus     string                 `protobuf:"bytes,5,opt,name=cmtStatus,proto3" json:"cmtStatus,omitempty"`
	Comments      []*CommentInfo         `protobuf:"bytes,6,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfo) Reset() {
	*x = PostInfo{}
	mi := &file_blog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfo) ProtoMessage() {}

func (x *PostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfo.ProtoReflect.Descriptor instead.
func (*PostInfo) Descriptor() ([]byte, []int) {
	return file_blog_proto_rawDescGZIP(), []int{15}
}

func (x *PostInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PostInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostInfo) GetCmtStatus() string {
	if x != nil {
		return x.CmtStatus
	}
	return ""
}

func (x *PostInfo) GetComments() []*CommentInfo {
	if x != nil {
		return x.Comments
	}
	return nil
}

type CommentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	UserId        uint32                 `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	PostId        int64                  `protobuf:"varint,4,opt,name=postId,proto3" json:"postId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentInfo) Reset() {
	*x = CommentInfo{}
	mi := &file_blog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentInfo) ProtoMessage() {}

func (x *CommentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_blog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentInfo.ProtoReflect.Descriptor instead.
func (*CommentInfo) Descriptor() ([]byte, []int) {
	return file_blog_proto_rawDescGZIP(), []int{16}
}

func (x *CommentInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentInfo) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentInfo) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

var File_blog_proto protoreflect.FileDescriptor

const file_blog_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"blog.proto\x12\x04blog\" \n" +
	"\x0eGetPostByIdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\",\n" +
	"\x12GetPostByUserIdReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\";\n" +
	"\x13GetPostByUserIdResp\x12$\n" +
	"\x05posts\x18\x01 \x03(\v2\x0e.blog.PostInfoR\x05posts\"+\n" +
	"\x11GetCurrentPostReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\":\n" +
	"\x12GetCurrentPostResp\x12$\n" +
	"\x05posts\x18\x01 \x03(\v2\x0e.blog.PostInfoR\x05posts\"T\n" +
	"\n" +
	"AddPostReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x03R\x06userId\"A\n" +
	"\vAddPostResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"g\n" +
	"\rUpdatePostReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x16\n" +
	"\x06userId\x18\x04 \x01(\x03R\x06userId\"D\n" +
	"\x0eUpdatePostResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"7\n" +
	"\rDeletePostReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\"D\n" +
	"\x0eDeletePostResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"]\n" +
	"\x11AddPostCommentReq\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\x03R\x06postId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x03R\x06userId\"H\n" +
	"\x12AddPostCommentResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x12GetPostCommentsReq\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\x03R\x06postId\"D\n" +
	"\x13GetPostCommentsResp\x12-\n" +
	"\bcomments\x18\x01 \x03(\v2\x11.blog.CommentInfoR\bcomments\"\xaf\x01\n" +
	"\bPostInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x16\n" +
	"\x06userId\x18\x04 \x01(\x03R\x06userId\x12\x1c\n" +
	"\tcmtStatus\x18\x05 \x01(\tR\tcmtStatus\x12-\n" +
	"\bcomments\x18\x06 \x03(\v2\x11.blog.CommentInfoR\bcomments\"g\n" +
	"\vCommentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\rR\x06userId\x12\x16\n" +
	"\x06postId\x18\x04 \x01(\x03R\x06postId2\xf7\x03\n" +
	"\x04Blog\x123\n" +
	"\vGetPostById\x12\x14.blog.GetPostByIdReq\x1a\x0e.blog.PostInfo\x12F\n" +
	"\x0fGetPostByUserId\x12\x18.blog.GetPostByUserIdReq\x1a\x19.blog.GetPostByUserIdResp\x12C\n" +
	"\x0eGetCurrentPost\x12\x17.blog.GetCurrentPostReq\x1a\x18.blog.GetCurrentPostResp\x12.\n" +
	"\aAddPost\x12\x10.blog.AddPostReq\x1a\x11.blog.AddPostResp\x127\n" +
	"\n" +
	"UpdatePost\x12\x13.blog.UpdatePostReq\x1a\x14.blog.UpdatePostResp\x127\n" +
	"\n" +
	"DeletePost\x12\x13.blog.DeletePostReq\x1a\x14.blog.DeletePostResp\x12C\n" +
	"\x0eAddPostComment\x12\x17.blog.AddPostCommentReq\x1a\x18.blog.AddPostCommentResp\x12F\n" +
	"\x0fGetPostComments\x12\x18.blog.GetPostCommentsReq\x1a\x19.blog.GetPostCommentsRespB\bZ\x06./blogb\x06proto3"

var (
	file_blog_proto_rawDescOnce sync.Once
	file_blog_proto_rawDescData []byte
)

func file_blog_proto_rawDescGZIP() []byte {
	file_blog_proto_rawDescOnce.Do(func() {
		file_blog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blog_proto_rawDesc), len(file_blog_proto_rawDesc)))
	})
	return file_blog_proto_rawDescData
}

var file_blog_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_blog_proto_goTypes = []any{
	(*GetPostByIdReq)(nil),      // 0: blog.GetPostByIdReq
	(*GetPostByUserIdReq)(nil),  // 1: blog.GetPostByUserIdReq
	(*GetPostByUserIdResp)(nil), // 2: blog.GetPostByUserIdResp
	(*GetCurrentPostReq)(nil),   // 3: blog.GetCurrentPostReq
	(*GetCurrentPostResp)(nil),  // 4: blog.GetCurrentPostResp
	(*AddPostReq)(nil),          // 5: blog.AddPostReq
	(*AddPostResp)(nil),         // 6: blog.AddPostResp
	(*UpdatePostReq)(nil),       // 7: blog.UpdatePostReq
	(*UpdatePostResp)(nil),      // 8: blog.UpdatePostResp
	(*DeletePostReq)(nil),       // 9: blog.DeletePostReq
	(*DeletePostResp)(nil),      // 10: blog.DeletePostResp
	(*AddPostCommentReq)(nil),   // 11: blog.AddPostCommentReq
	(*AddPostCommentResp)(nil),  // 12: blog.AddPostCommentResp
	(*GetPostCommentsReq)(nil),  // 13: blog.GetPostCommentsReq
	(*GetPostCommentsResp)(nil), // 14: blog.GetPostCommentsResp
	(*PostInfo)(nil),            // 15: blog.PostInfo
	(*CommentInfo)(nil),         // 16: blog.CommentInfo
}
var file_blog_proto_depIdxs = []int32{
	15, // 0: blog.GetPostByUserIdResp.posts:type_name -> blog.PostInfo
	15, // 1: blog.GetCurrentPostResp.posts:type_name -> blog.PostInfo
	16, // 2: blog.GetPostCommentsResp.comments:type_name -> blog.CommentInfo
	16, // 3: blog.PostInfo.comments:type_name -> blog.CommentInfo
	0,  // 4: blog.Blog.GetPostById:input_type -> blog.GetPostByIdReq
	1,  // 5: blog.Blog.GetPostByUserId:input_type -> blog.GetPostByUserIdReq
	3,  // 6: blog.Blog.GetCurrentPost:input_type -> blog.GetCurrentPostReq
	5,  // 7: blog.Blog.AddPost:input_type -> blog.AddPostReq
	7,  // 8: blog.Blog.UpdatePost:input_type -> blog.UpdatePostReq
	9,  // 9: blog.Blog.DeletePost:input_type -> blog.DeletePostReq
	11, // 10: blog.Blog.AddPostComment:input_type -> blog.AddPostCommentReq
	13, // 11: blog.Blog.GetPostComments:input_type -> blog.GetPostCommentsReq
	15, // 12: blog.Blog.GetPostById:output_type -> blog.PostInfo
	2,  // 13: blog.Blog.GetPostByUserId:output_type -> blog.GetPostByUserIdResp
	4,  // 14: blog.Blog.GetCurrentPost:output_type -> blog.GetCurrentPostResp
	6,  // 15: blog.Blog.AddPost:output_type -> blog.AddPostResp
	8,  // 16: blog.Blog.UpdatePost:output_type -> blog.UpdatePostResp
	10, // 17: blog.Blog.DeletePost:output_type -> blog.DeletePostResp
	12, // 18: blog.Blog.AddPostComment:output_type -> blog.AddPostCommentResp
	14, // 19: blog.Blog.GetPostComments:output_type -> blog.GetPostCommentsResp
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_blog_proto_init() }
func file_blog_proto_init() {
	if File_blog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blog_proto_rawDesc), len(file_blog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blog_proto_goTypes,
		DependencyIndexes: file_blog_proto_depIdxs,
		MessageInfos:      file_blog_proto_msgTypes,
	}.Build()
	File_blog_proto = out.File
	file_blog_proto_goTypes = nil
	file_blog_proto_depIdxs = nil
}
